# Generated by Django 5.1.2 on 2024-11-20 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicemodel",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="device_images/",
                verbose_name="Изображение",
            ),
        ),
    ]
